db:
  image: mongo
  # volumes:
  #   - './data:/data/db'
  expose:
    - "27017"
    - "37017"
  command: --smallfiles
  restart: always
prerender:
  image: mondora/prerender
  ports:
    - "3000:3000"
  restart: always
web:
  build: .
  expose:
    - "80"
  env_file:
    - meanbase.env
  restart: always
  links:
      - db:db
nginx:
  restart: always
  build: nginx
  links:
    - web:web
    - prerender:prerender
  volumes_from:
    - web
  ports:
    - "80:80"
